items_ = [
    {"name": "Флаг Украины", "price": 1999, "chance_drop": 0.4, "icon": "🇺🇦"},
    {"name": "Флаг России", "price": 1111, "chance_drop": 0.8, "icon": "🇷🇺"},
    {"name": "Флаг Беларуси", "price": 1500, "chance_drop": 0.75, "icon": "🇧🇾"},
    {"name": "Флаг США", "price": 15000, "chance_drop": 0.1, "icon": "🇺🇸"},
    {"name": "Флаг Таджикистана", "price": 400, "chance_drop": 0.5, "icon": "🇹🇯"},
    {"name": "Флаг Узбекистана", "price": 400, "chance_drop": 0.5, "icon": "🇺🇿"},
    {"name": "Флаг Арабских Эмиратов", "price": 50000, "chance_drop": 0.1, "icon": "🇦🇪"},
    {"name": "Флаг Канады", "price": 200, "chance_drop": 0.7, "icon": "🇨🇦"},
    {"name": "Флаг Нидерландов", "price": 9000, "chance_drop": 0.2, "icon": "🇳🇱"},
    {"name": "Флаг Мексики", "price": 10, "chance_drop": 0.99, "icon": "🇲🇽"},

    {"name": "Фото Жорика", "price": 99999, "chance_drop": 0.03, "icon": "🖼"},
    {"name": "Фото какого-то негра", "price": 20, "chance_drop": 1, "icon": "🖼"},
    {"name": "Фото Москвы", "price": 150, "chance_drop": 0.8, "icon": "🖼"},
    {"name": "Фото Моргенштерна", "price": 1, "chance_drop": 1, "icon": "🖼"},
    {"name": "Фото Киева", "price": 50000, "chance_drop": 0.04, "icon": "🖼"},
    {"name": "Фото Зубенко Михала Петровича", "price": 1930, "chance_drop": 0.5, "icon": "🖼"},

    {"name": "Табличка «Иди нахер»", "price": 777777, "chance_drop": 0.001, "icon": "🪧"},
    {"name": "Табличка «Путин хуйло»", "price": 666666, "chance_drop": 0.01, "icon": "🪧"},
    {"name": "Табличка «Жорика здесь нет»", "price": 1500, "chance_drop": 0.85, "icon": "🪧"},
    {"name": "Табличка «По башке себе постучи»", "price": 8900, "chance_drop": 0.3, "icon": "🪧"},
    {"name": "Табличка «Играю в майнкрафт»", "price": 1000, "chance_drop": 0.95, "icon": "🪧"},
    {"name": "Табличка «Не беспокоить, дрочу»", "price": 999, "chance_drop": 0.96, "icon": "🪧"},
    {"name": "Табличка «Я знаю кто ты»", "price": 9999, "chance_drop": 0.2, "icon": "🪧"},
    {"name": "Табличка «Го аниме»", "price": 1000000, "chance_drop": 0.003, "icon": "🪧"},
    {"name": "Табличка «Продам Жигуль»", "price": 444, "chance_drop": 0.98, "icon": "🪧"},
    {"name": "Табличка «Продам Трактор»", "price": 10300, "chance_drop": 0.25, "icon": "🪧"},

    {"name": "Просроченные чипсы", "price": 3, "chance_drop": 0.99, "icon": "🥔"},
    {"name": "Чипсы", "price": 30, "chance_drop": 0.98, "icon": "🥔"},
    {"name": "Картошка", "price": 20, "chance_drop": 0.98, "icon": "🥔"},
    {"name": "Бургер", "price": 45, "chance_drop": 0.95, "icon": "🍔"},
    {"name": "Доширак", "price": 10, "chance_drop": 0.99, "icon": "🍝"},
    {"name": "Мивина", "price": 14, "chance_drop": 0.98, "icon": "🍝"},
    {"name": "Хлеб", "price": 8, "chance_drop": 0.99, "icon": "🍞"},
]
