items_ = [
    {'id': 0, 'name': 'Флаг Украины', 'price': 1999, 'chance_drop': 0.4, 'icon': '🇺🇦'},
    {'id': 1, 'name': 'Флаг России', 'price': 1111, 'chance_drop': 0.8, 'icon': '🇷🇺'},
    {'id': 2, 'name': 'Флаг Беларуси', 'price': 1500, 'chance_drop': 0.75, 'icon': '🇧🇾'},
    {'id': 3, 'name': 'Флаг США', 'price': 15000, 'chance_drop': 0.1, 'icon': '🇺🇸'},
    {'id': 4, 'name': 'Флаг Таджикистана', 'price': 400, 'chance_drop': 0.5, 'icon': '🇹🇯'},
    {'id': 5, 'name': 'Флаг Узбекистана', 'price': 400, 'chance_drop': 0.5, 'icon': '🇺🇿'},
    {'id': 6, 'name': 'Флаг Арабских Эмиратов', 'price': 50000, 'chance_drop': 0.1, 'icon': '🇦🇪'},
    {'id': 7, 'name': 'Флаг Канады', 'price': 200, 'chance_drop': 0.7, 'icon': '🇨🇦'},
    {'id': 8, 'name': 'Флаг Нидерландов', 'price': 9000, 'chance_drop': 0.2, 'icon': '🇳🇱'},
    {'id': 9, 'name': 'Флаг Мексики', 'price': 10, 'chance_drop': 0.99, 'icon': '🇲🇽'},
    {'id': 10, 'name': 'Фото Жорика', 'price': 99999, 'chance_drop': 0.03, 'icon': '🖼'},
    {'id': 11, 'name': 'Фото какого-то негра', 'price': 20, 'chance_drop': 1, 'icon': '🖼'},
    {'id': 12, 'name': 'Фото Москвы', 'price': 150, 'chance_drop': 0.8, 'icon': '🖼'},
    {'id': 13, 'name': 'Фото Моргенштерна', 'price': 1, 'chance_drop': 1, 'icon': '🖼'},
    {'id': 14, 'name': 'Фото Киева', 'price': 50000, 'chance_drop': 0.04, 'icon': '🖼'},
    {'id': 15, 'name': 'Фото Зубенко Михала Петровича', 'price': 1930, 'chance_drop': 0.5, 'icon': '🖼'},
    {'id': 16, 'name': 'Табличка «Иди нахер»', 'price': 777777, 'chance_drop': 0.001, 'icon': '\U0001faa7'},
    {'id': 17, 'name': 'Табличка «Путин хуйло»', 'price': 666666, 'chance_drop': 0.01, 'icon': '\U0001faa7'},
    {'id': 18, 'name': 'Табличка «Жорика здесь нет»', 'price': 1500, 'chance_drop': 0.85, 'icon': '\U0001faa7'},
    {'id': 19, 'name': 'Табличка «По башке себе постучи»', 'price': 8900, 'chance_drop': 0.3, 'icon': '\U0001faa7'},
    {'id': 20, 'name': 'Табличка «Играю в майнкрафт»', 'price': 1000, 'chance_drop': 0.95, 'icon': '\U0001faa7'},
    {'id': 21, 'name': 'Табличка «Не беспокоить, дрочу»', 'price': 999, 'chance_drop': 0.96, 'icon': '\U0001faa7'},
    {'id': 22, 'name': 'Табличка «Я знаю кто ты»', 'price': 9999, 'chance_drop': 0.2, 'icon': '\U0001faa7'},
    {'id': 23, 'name': 'Табличка «Го аниме»', 'price': 1999999, 'chance_drop': 0.003, 'icon': '\U0001faa7'},
    {'id': 24, 'name': 'Табличка «Продам Жигуль»', 'price': 444, 'chance_drop': 0.98, 'icon': '\U0001faa7'},
    {'id': 25, 'name': 'Табличка «Продам Трактор»', 'price': 10300, 'chance_drop': 0.25, 'icon': '\U0001faa7'},
    {'id': 26, 'name': 'Просроченные чипсы', 'price': 3, 'chance_drop': 0.99, 'icon': '🥔'},
    {'id': 27, 'name': 'Чипсы', 'price': 30, 'chance_drop': 0.98, 'icon': '🥔'},
    {'id': 28, 'name': 'Картошка', 'price': 20, 'chance_drop': 0.98, 'icon': '🥔'},
    {'id': 29, 'name': 'Бургер', 'price': 45, 'chance_drop': 0.95, 'icon': '🍔'},
    {'id': 30, 'name': 'Доширак', 'price': 10, 'chance_drop': 0.99, 'icon': '🍝'},
    {'id': 31, 'name': 'Мивина', 'price': 14, 'chance_drop': 0.98, 'icon': '🍝'},
    {'id': 32, 'name': 'Хлеб', 'price': 8, 'chance_drop': 0.99, 'icon': '🍞'},
    {'id': 33, 'name': 'Шоколадка', 'price': 100, 'chance_drop': 0.9, 'icon': '🍫'},
    {'id': 34, 'name': 'Суши', 'price': 1500, 'chance_drop': 0.7, 'icon': '🍣'},
    {'id': 35, 'name': 'Пирог', 'price': 5000, 'chance_drop': 0.4, 'icon': '🥮'},
    {'id': 36, 'name': 'Резиновый писюн', 'price': 300, 'chance_drop': 0.99, 'icon': '🍆'},
    {'id': 37, 'name': 'Сигареты', 'price': 50, 'chance_drop': 0.9, 'icon': '🚬'},
    {'id': 38, 'name': 'Балтика 9', 'price': 50, 'chance_drop': 0.9, 'icon': '🍺'},
    {'id': 39, 'name': 'Вибратор', 'price': 500, 'chance_drop': 0.95, 'icon': '🍆'},
    {'id': 40, 'name': 'Пистолет', 'price': 150000, 'chance_drop': 0.05, 'icon': '🔫'},
    {'id': 41, 'name': 'Песня "Путин молодец"', 'price': 900000, 'chance_drop': 0.02, 'icon': '📀'},
    {'id': 42, 'name': 'Песня "Я ебу собак"', 'price': 1700000, 'chance_drop': 0.007, 'icon': '📀'},
    {'id': 43, 'name': 'Пистолет с гравировкой "Алёша"', 'price': 150001, 'chance_drop': 0.05, 'icon': '🔫'},
]
